// <auto-generated />
using ADWA.DataBase;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ADWA.Migrations
{
    [DbContext(typeof(DBContext))]
    partial class DBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.1");

            modelBuilder.Entity("ADWA.Models.ApplicationUser", b =>
                {
                    b.Property<string>("SamAccountName")
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "SamAccountName");

                    b.Property<string>("DateOfDisconnect")
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "DateOfDisconnect");

                    b.Property<string>("DistinguishedName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "DistinguishedName");

                    b.Property<string>("GivenName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "GivenName");

                    b.Property<bool>("IsDialInEnabled")
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Relational:JsonPropertyName", "IsDialInEnabled");

                    b.Property<string>("Surname")
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "Surname");

                    b.HasKey("SamAccountName");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
